2018-12-09 12:10:44 DEBUG db_query [db.py-16] select * from `user` where `name`='张三'
2018-12-09 12:10:44 DEBUG db_query [db.py-21] ((9593, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
2018-12-09 12:10:44 INFO <module> [run_all.py-14] 测试开始==================================================
2018-12-09 12:10:45 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:10:45 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
2018-12-09 12:10:45 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:10:45 INFO case_log_info [case_log.py-5] 执行用例：test_login_normal
2018-12-09 12:10:45 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/login/
2018-12-09 12:10:45 INFO case_log_info [case_log.py-7] 请求数据：{ "name": "wangwu002","password": "123456"}
2018-12-09 12:10:45 INFO case_log_info [case_log.py-8] 期望结果："<h1>登录成功</h1>"
2018-12-09 12:10:45 INFO case_log_info [case_log.py-9] 实际结果：<h1>登录成功</h1>
2018-12-09 12:10:45 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:10:45 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
2018-12-09 12:10:45 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:10:45 INFO case_log_info [case_log.py-5] 执行用例：test_login_password_wrong
2018-12-09 12:10:45 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/login/
2018-12-09 12:10:45 INFO case_log_info [case_log.py-7] 请求数据：{"name": "张三好","password": "111111"}
2018-12-09 12:10:45 INFO case_log_info [case_log.py-8] 期望结果："用户名或密码错误"
2018-12-09 12:10:45 INFO case_log_info [case_log.py-9] 实际结果：<h1>失败，用户名或密码错误</h1>
2018-12-09 12:10:45 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:10:45 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 149
2018-12-09 12:10:45 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:10:45 INFO case_log_info [case_log.py-5] 执行用例：test_reg_user_exis
2018-12-09 12:10:45 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/reg/
2018-12-09 12:10:45 INFO case_log_info [case_log.py-7] 请求数据：{"name": "wangwu002","password": "123456"}
2018-12-09 12:10:45 INFO case_log_info [case_log.py-8] 期望结果：{
    "code": "100001",
    "data": {
        "name": "wangwu002",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "失败，用户已存在"
}
2018-12-09 12:10:45 INFO case_log_info [case_log.py-9] 实际结果：{"code":"100001","data":{"name":"wangwu002","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u5931\u8d25\uff0c\u7528\u6237\u5df2\u5b58\u5728"}

2018-12-09 12:10:45 INFO <module> [run_all.py-21] 测试结束==================================================
2018-12-09 12:12:01 DEBUG db_query [db.py-16] select * from `user` where `name`='张三'
2018-12-09 12:12:01 DEBUG db_query [db.py-21] ((9593, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
2018-12-09 12:12:01 INFO <module> [run_all.py-14] 测试开始==================================================
2018-12-09 12:12:02 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:12:02 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
2018-12-09 12:12:02 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:12:02 INFO case_log_info [case_log.py-5] 执行用例：test_login_normal
2018-12-09 12:12:02 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/login/
2018-12-09 12:12:02 INFO case_log_info [case_log.py-7] 请求数据：{ "name": "wangwu002","password": "123456"}
2018-12-09 12:12:02 INFO case_log_info [case_log.py-8] 期望结果："<h1>登录成功</h1>"
2018-12-09 12:12:02 INFO case_log_info [case_log.py-9] 实际结果：<h1>登录成功</h1>
2018-12-09 12:12:02 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:12:02 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
2018-12-09 12:12:02 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:12:02 INFO case_log_info [case_log.py-5] 执行用例：test_login_password_wrong
2018-12-09 12:12:02 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/login/
2018-12-09 12:12:02 INFO case_log_info [case_log.py-7] 请求数据：{"name": "张三好","password": "111111"}
2018-12-09 12:12:02 INFO case_log_info [case_log.py-8] 期望结果："用户名或密码错误"
2018-12-09 12:12:02 INFO case_log_info [case_log.py-9] 实际结果：<h1>失败，用户名或密码错误</h1>
2018-12-09 12:12:02 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:12:02 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 149
2018-12-09 12:12:02 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:12:02 INFO case_log_info [case_log.py-5] 执行用例：test_reg_user_exis
2018-12-09 12:12:02 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/reg/
2018-12-09 12:12:02 INFO case_log_info [case_log.py-7] 请求数据：{"name": "wangwu002","password": "123456"}
2018-12-09 12:12:02 INFO case_log_info [case_log.py-8] 期望结果：{
    "code": "100001",
    "data": {
        "name": "wangwu002",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "失败，用户已存在"
}
2018-12-09 12:12:02 INFO case_log_info [case_log.py-9] 实际结果：{"code":"100001","data":{"name":"wangwu002","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u5931\u8d25\uff0c\u7528\u6237\u5df2\u5b58\u5728"}

2018-12-09 12:12:02 INFO <module> [run_all.py-21] 测试结束==================================================
2018-12-09 12:13:19 DEBUG db_query [db.py-16] select * from `user` where `name`='张三'
2018-12-09 12:13:19 DEBUG db_query [db.py-21] ((9593, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
2018-12-09 12:13:19 INFO <module> [run_all.py-14] 测试开始==================================================
2018-12-09 12:13:19 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:13:20 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
2018-12-09 12:13:20 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:13:20 INFO case_log_info [case_log.py-5] 执行用例：test_login_normal
2018-12-09 12:13:20 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/login/
2018-12-09 12:13:20 INFO case_log_info [case_log.py-7] 请求数据：{ "name": "wangwu002","password": "123456"}
2018-12-09 12:13:20 INFO case_log_info [case_log.py-8] 期望结果："<h1>登录成功</h1>"
2018-12-09 12:13:20 INFO case_log_info [case_log.py-9] 实际结果：<h1>登录成功</h1>
2018-12-09 12:13:20 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:13:20 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
2018-12-09 12:13:20 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:13:20 INFO case_log_info [case_log.py-5] 执行用例：test_login_password_wrong
2018-12-09 12:13:20 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/login/
2018-12-09 12:13:20 INFO case_log_info [case_log.py-7] 请求数据：{"name": "张三好","password": "111111"}
2018-12-09 12:13:20 INFO case_log_info [case_log.py-8] 期望结果："用户名或密码错误"
2018-12-09 12:13:20 INFO case_log_info [case_log.py-9] 实际结果：<h1>失败，用户名或密码错误</h1>
2018-12-09 12:13:20 DEBUG db_query [db.py-16] select * from `user` where `name`='wangwu005'
2018-12-09 12:13:20 DEBUG db_query [db.py-21] ()
2018-12-09 12:13:20 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:13:20 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 113
2018-12-09 12:13:20 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:13:20 INFO case_log_info [case_log.py-5] 执行用例：test_reg_normal
2018-12-09 12:13:20 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/reg/
2018-12-09 12:13:20 INFO case_log_info [case_log.py-7] 请求数据：{"name": "wangwu005", "password": "123456"}
2018-12-09 12:13:20 INFO case_log_info [case_log.py-8] 期望结果：{
    "code": "100000",
    "data": {
        "name": "wangwu005",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "成功"
}
2018-12-09 12:13:20 INFO case_log_info [case_log.py-9] 实际结果：{"code":"100000","data":{"name":"wangwu005","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u6210\u529f"}

2018-12-09 12:13:20 DEBUG db_change [db.py-27] delete from `user` where `name`='wangwu005'
2018-12-09 12:13:20 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:13:20 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 149
2018-12-09 12:13:20 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:13:20 INFO case_log_info [case_log.py-5] 执行用例：test_reg_user_exis
2018-12-09 12:13:20 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/reg/
2018-12-09 12:13:20 INFO case_log_info [case_log.py-7] 请求数据：{"name": "wangwu002","password": "123456"}
2018-12-09 12:13:20 INFO case_log_info [case_log.py-8] 期望结果：{
    "code": "100001",
    "data": {
        "name": "wangwu002",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "失败，用户已存在"
}
2018-12-09 12:13:20 INFO case_log_info [case_log.py-9] 实际结果：{"code":"100001","data":{"name":"wangwu002","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u5931\u8d25\uff0c\u7528\u6237\u5df2\u5b58\u5728"}

2018-12-09 12:13:20 INFO <module> [run_all.py-21] 测试结束==================================================
2018-12-09 12:14:22 DEBUG db_query [db.py-16] select * from `user` where `name`='张三'
2018-12-09 12:14:22 DEBUG db_query [db.py-21] ((9593, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
2018-12-09 12:14:22 INFO <module> [run_all.py-14] 测试开始==================================================
2018-12-09 12:14:23 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:14:23 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
2018-12-09 12:14:23 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:14:23 INFO case_log_info [case_log.py-5] 执行用例：test_login_normal
2018-12-09 12:14:23 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/login/
2018-12-09 12:14:23 INFO case_log_info [case_log.py-7] 请求数据：{ "name": "wangwu002","password": "123456"}
2018-12-09 12:14:23 INFO case_log_info [case_log.py-8] 期望结果："<h1>登录成功</h1>"
2018-12-09 12:14:23 INFO case_log_info [case_log.py-9] 实际结果：<h1>登录成功</h1>
2018-12-09 12:14:23 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:14:23 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
2018-12-09 12:14:23 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:14:23 INFO case_log_info [case_log.py-5] 执行用例：test_login_password_wrong
2018-12-09 12:14:23 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/login/
2018-12-09 12:14:23 INFO case_log_info [case_log.py-7] 请求数据：{"name": "张三好","password": "111111"}
2018-12-09 12:14:23 INFO case_log_info [case_log.py-8] 期望结果："用户名或密码错误"
2018-12-09 12:14:23 INFO case_log_info [case_log.py-9] 实际结果：<h1>失败，用户名或密码错误</h1>
2018-12-09 12:14:23 DEBUG db_query [db.py-16] select * from `user` where `name`='wangwu005'
2018-12-09 12:14:23 DEBUG db_query [db.py-21] ()
2018-12-09 12:14:23 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:14:23 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 113
2018-12-09 12:14:23 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:14:23 INFO case_log_info [case_log.py-5] 执行用例：test_reg_normal
2018-12-09 12:14:23 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/reg/
2018-12-09 12:14:23 INFO case_log_info [case_log.py-7] 请求数据：{"name": "wangwu005", "password": "123456"}
2018-12-09 12:14:23 INFO case_log_info [case_log.py-8] 期望结果：{
    "code": "100000",
    "data": {
        "name": "wangwu005",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "成功"
}
2018-12-09 12:14:23 INFO case_log_info [case_log.py-9] 实际结果：{"code":"100000","data":{"name":"wangwu005","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u6210\u529f"}

2018-12-09 12:14:23 DEBUG db_change [db.py-27] delete from `user` where `name`='wangwu005'
2018-12-09 12:14:23 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:14:23 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 149
2018-12-09 12:14:23 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:14:23 INFO case_log_info [case_log.py-5] 执行用例：test_reg_user_exis
2018-12-09 12:14:23 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/reg/
2018-12-09 12:14:23 INFO case_log_info [case_log.py-7] 请求数据：{"name": "wangwu002","password": "123456"}
2018-12-09 12:14:23 INFO case_log_info [case_log.py-8] 期望结果：{
    "code": "100001",
    "data": {
        "name": "wangwu002",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "失败，用户已存在"
}
2018-12-09 12:14:23 INFO case_log_info [case_log.py-9] 实际结果：{"code":"100001","data":{"name":"wangwu002","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u5931\u8d25\uff0c\u7528\u6237\u5df2\u5b58\u5728"}

2018-12-09 12:15:05 DEBUG db_query [db.py-16] select * from `user` where `name`='张三'
2018-12-09 12:15:05 DEBUG db_query [db.py-21] ((9593, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
2018-12-09 12:15:05 INFO <module> [run_all.py-14] 测试开始==================================================
2018-12-09 12:15:05 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:15:05 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
2018-12-09 12:15:05 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:15:05 INFO case_log_info [case_log.py-5] 执行用例：test_login_normal
2018-12-09 12:15:05 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/login/
2018-12-09 12:15:05 INFO case_log_info [case_log.py-7] 请求数据：{ "name": "wangwu002","password": "123456"}
2018-12-09 12:15:05 INFO case_log_info [case_log.py-8] 期望结果："<h1>登录成功</h1>"
2018-12-09 12:15:05 INFO case_log_info [case_log.py-9] 实际结果：<h1>登录成功</h1>
2018-12-09 12:15:05 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:15:05 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
2018-12-09 12:15:05 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:15:05 INFO case_log_info [case_log.py-5] 执行用例：test_login_password_wrong
2018-12-09 12:15:05 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/login/
2018-12-09 12:15:05 INFO case_log_info [case_log.py-7] 请求数据：{"name": "张三好","password": "111111"}
2018-12-09 12:15:05 INFO case_log_info [case_log.py-8] 期望结果："用户名或密码错误"
2018-12-09 12:15:05 INFO case_log_info [case_log.py-9] 实际结果：<h1>失败，用户名或密码错误</h1>
2018-12-09 12:15:05 DEBUG db_query [db.py-16] select * from `user` where `name`='wangwu005'
2018-12-09 12:15:06 DEBUG db_query [db.py-21] ()
2018-12-09 12:15:06 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:15:06 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 113
2018-12-09 12:15:06 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:15:06 INFO case_log_info [case_log.py-5] 执行用例：test_reg_normal
2018-12-09 12:15:06 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/reg/
2018-12-09 12:15:06 INFO case_log_info [case_log.py-7] 请求数据：{"name": "wangwu005", "password": "123456"}
2018-12-09 12:15:06 INFO case_log_info [case_log.py-8] 期望结果：{
    "code": "100000",
    "data": {
        "name": "wangwu005",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "成功"
}
2018-12-09 12:15:06 INFO case_log_info [case_log.py-9] 实际结果：{"code":"100000","data":{"name":"wangwu005","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u6210\u529f"}

2018-12-09 12:15:06 DEBUG db_change [db.py-27] delete from `user` where `name`='wangwu005'
2018-12-09 12:15:07 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 12:15:07 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 149
2018-12-09 12:15:07 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 12:15:07 INFO case_log_info [case_log.py-5] 执行用例：test_reg_user_exis
2018-12-09 12:15:07 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/reg/
2018-12-09 12:15:07 INFO case_log_info [case_log.py-7] 请求数据：{"name": "wangwu002","password": "123456"}
2018-12-09 12:15:07 INFO case_log_info [case_log.py-8] 期望结果：{
    "code": "100001",
    "data": {
        "name": "wangwu002",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "失败，用户已存在"
}
2018-12-09 12:15:07 INFO case_log_info [case_log.py-9] 实际结果：{"code":"100001","data":{"name":"wangwu002","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u5931\u8d25\uff0c\u7528\u6237\u5df2\u5b58\u5728"}

2018-12-09 12:15:09 INFO <module> [run_all.py-20] 邮件发送成功
2018-12-09 12:15:09 INFO <module> [run_all.py-21] 测试结束==================================================
2018-12-09 13:51:53 DEBUG db_query [db.py-16] select * from `user` where `name`='张三'
2018-12-09 13:51:53 DEBUG db_query [db.py-21] ((9593, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
2018-12-09 13:51:53 INFO <module> [run_all.py-14] 测试开始==================================================
2018-12-09 13:51:53 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 13:51:53 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
2018-12-09 13:51:53 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 13:51:53 INFO case_log_info [case_log.py-5] 执行用例：test_login_normal
2018-12-09 13:51:53 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/login/
2018-12-09 13:51:53 INFO case_log_info [case_log.py-7] 请求数据：{ "name": "wangwu002","password": "123456"}
2018-12-09 13:51:53 INFO case_log_info [case_log.py-8] 期望结果："<h1>登录成功</h1>"
2018-12-09 13:51:53 INFO case_log_info [case_log.py-9] 实际结果：<h1>登录成功</h1>
2018-12-09 13:51:53 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 13:51:54 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
2018-12-09 13:51:54 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 13:51:54 INFO case_log_info [case_log.py-5] 执行用例：test_login_password_wrong
2018-12-09 13:51:54 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/login/
2018-12-09 13:51:54 INFO case_log_info [case_log.py-7] 请求数据：{"name": "张三好","password": "111111"}
2018-12-09 13:51:54 INFO case_log_info [case_log.py-8] 期望结果："用户名或密码错误"
2018-12-09 13:51:54 INFO case_log_info [case_log.py-9] 实际结果：<h1>失败，用户名或密码错误</h1>
2018-12-09 13:51:54 DEBUG db_query [db.py-16] select * from `user` where `name`='wangwu005'
2018-12-09 13:51:54 DEBUG db_query [db.py-21] ()
2018-12-09 13:51:54 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 13:51:54 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 113
2018-12-09 13:51:54 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 13:51:54 INFO case_log_info [case_log.py-5] 执行用例：test_reg_normal
2018-12-09 13:51:54 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/reg/
2018-12-09 13:51:54 INFO case_log_info [case_log.py-7] 请求数据：{"name": "wangwu005", "password": "123456"}
2018-12-09 13:51:54 INFO case_log_info [case_log.py-8] 期望结果：{
    "code": "100000",
    "data": {
        "name": "wangwu005",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "成功"
}
2018-12-09 13:51:54 INFO case_log_info [case_log.py-9] 实际结果：{"code":"100000","data":{"name":"wangwu005","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u6210\u529f"}

2018-12-09 13:51:54 DEBUG db_change [db.py-27] delete from `user` where `name`='wangwu005'
2018-12-09 13:51:54 DEBUG _new_conn [connectionpool.py-205] Starting new HTTP connection (1): 115.28.108.130:5000
2018-12-09 13:51:54 DEBUG _make_request [connectionpool.py-393] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 149
2018-12-09 13:51:54 INFO case_log_info [case_log.py-4] ----------------------------------------------------------------------------------------------------
2018-12-09 13:51:54 INFO case_log_info [case_log.py-5] 执行用例：test_reg_user_exis
2018-12-09 13:51:54 INFO case_log_info [case_log.py-6] 接口地址：http://115.28.108.130:5000/api/user/reg/
2018-12-09 13:51:54 INFO case_log_info [case_log.py-7] 请求数据：{"name": "wangwu002","password": "123456"}
2018-12-09 13:51:54 INFO case_log_info [case_log.py-8] 期望结果：{
    "code": "100001",
    "data": {
        "name": "wangwu002",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "失败，用户已存在"
}
2018-12-09 13:51:54 INFO case_log_info [case_log.py-9] 实际结果：{"code":"100001","data":{"name":"wangwu002","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u5931\u8d25\uff0c\u7528\u6237\u5df2\u5b58\u5728"}

2018-12-09 13:51:55 INFO <module> [run_all.py-20] 邮件发送成功
2018-12-09 13:51:55 INFO <module> [run_all.py-21] 测试结束==================================================
